# Site settings
title: Just2us Blog
email: junda@just2us.com
copyright_name: Just2us
author_name: Ong Jun Da
description: Creating Apps We Love
baseurl: ""
url: https://blog.just2us.com

twitter_username: samwize
github_username:  samwize
facebook_username:  ongjunda
email_username:  junda@just2us.com
disqus: just2us
adsense_client: ca-pub-8504591086876220
adsense_slot: 3185604309
google_analytics: UA-8780506-1

# Default header image
defaults:
  - scope:
      path: ""
    values:
      image: /img/sf-golden-gate.jpg

# SEO
logo: /img/favicon-192.png
twitter:
  username: samwize
  card: summary
author:
  twitter: samwize
facebook:
  admins: 704185456
social:
  name: Junda Ong
  links:
    - https://twitter.com/samwize
    - https://www.facebook.com/ongjunda
    - https://www.linkedin.com/in/junda
    - https://github.com/samwize

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  hard_wrap: true # newline becomes <br />
